version: '3'
services: 
        webapp:
                container_name: webapp 
                build: ./webapp
                ports:
                        - "8080:8080"
                volumes:
                        - ./webapp/src:/src
